name: $(Date:yyyyMMdd)-$(Hours)-$(Minutes)

resources:
  repositories:
  - repository: github
    type: github
    name: pallxk/document-installed-item
    ref: version.sh
    endpoint: pallxk

trigger:
- master

schedules:
- cron: 0 12 * * *
  displayName: Daily update
  branches:
    include:
    - master
  always: true  # Run even if no source code changes

jobs:
- job: run_ubuntu_1604
  pool:
    vmImage: ubuntu-16.04
  steps:
  - checkout: github

  - bash: $(Build.SourcesDirectory)/version.sh
    displayName: 'Bash: ./version.sh'

- job: run_ubuntu_1804
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: github

  - bash: $(Build.SourcesDirectory)/version.sh
    displayName: 'Bash: ./version.sh'
