name: $(Date:yyyyMMdd)-$(Hours)-$(Minutes)

trigger:
- master

schedules:
- cron: 0 12 * * *
  displayName: Daily update
  branches:
    include:
    - master
  always: true  # Run even if no source code changes

stages:
- stage: generate_commit_and_test
  displayName: Generate, Commit, and Test
  jobs:
  - job: generate_commit_and_test
    displayName: Generate, Commit, and Test
    pool:
      vmImage: ubuntu-18.04
    steps:
    - checkout: self
      persistCredentials: true

    - bash: $(Build.SourcesDirectory)/generate-and-commit
      displayName: 'Bash: ./generate-and-commit'

    - bash: $(Build.SourcesDirectory)/version.sh
      displayName: 'Bash: ./version.sh'
