#!/bin/sh

set -eux

dirname=$(dirname "$0")
date=$(date -Is)

cd "$dirname"

git config user.name || git config user.name bot
git config user.email || git config user.email bot@pallxk.com

git checkout version.sh
./generate-version-script
git add -f version.sh
# There may be no changes made to the version.sh script
git commit -m "version.sh: $date" && git push || true
